// Generated by https://quicktype.io

export interface ResponseOptions {
  count: number;
  parentNames: ParentName[];
  data: Data[];
}

export interface Data {
  _id: string;
  title: string;
  patternId: string;
  __v: number;
}

export interface ParentName {
  name: string;
}

export interface SelectsContent {
  selects: ResponseOptions[];
}
